sex: 1 for female and 2 for male.
age: of the patient.
classification: covid test findings. Values 1-3 mean that the patient was diagnosed with covid in different
degrees. 4 or higher means that the patient is not a carrier of covid or that the test is inconclusive.
patient type: type of care the patient received in the unit. 1 for returned home and 2 for hospitalization.
pneumonia: whether the patient already have air sacs inflammation or not.
pregnancy: whether the patient is pregnant or not.
diabetes: whether the patient has diabetes or not.
copd: Indicates whether the patient has Chronic obstructive pulmonary disease or not.
asthma: whether the patient has asthma or not.
inmsupr: whether the patient is immunosuppressed or not.
hypertension: whether the patient has hypertension or not.
cardiovascular: whether the patient has heart or blood vessels related disease.
renal chronic: whether the patient has chronic renal disease or not.
other disease: whether the patient has other disease or not.
obesity: whether the patient is obese or not.
tobacco: whether the patient is a tobacco user.
usmr: Indicates whether the patient treated medical units of the first, second or third level.
medical unit: type of institution of the National Health System that provided the care.
intubed: whether the patient was connected to the ventilator.
icu: Indicates whether the patient had been admitted to an Intensive Care Unit.
date died: If the patient died indicate the date of death, and 9999-99-99 otherwise.

In [3]:
import pandas as pd 
df=pd.read_csv("Covid Data.csv")
df

USMER  MEDICAL_UNIT  SEX  PATIENT_TYPE   DATE_DIED  INTUBED  \
0            2             1    1             1  03/05/2020       97   
1            2             1    2             1  03/06/2020       97   
2            2             1    2             2  09/06/2020        1   
3            2             1    1             1  12/06/2020       97   
4            2             1    2             1  21/06/2020       97   
...        ...           ...  ...           ...         ...      ...   
1048570      2            13    2             1  9999-99-99       97   
1048571      1            13    2             2  9999-99-99        2   
1048572      2            13    2             1  9999-99-99       97   
1048573      2            13    2             1  9999-99-99       97   
1048574      2            13    2             1  9999-99-99       97   

         PNEUMONIA  AGE  PREGNANT  DIABETES  ...  ASTHMA  INMSUPR  \
0                1   65         2         2  ...       2        2   
1                1   72        97         2  ...       2        2   
2                2   55        97         1  ...       2        2   
3                2   53         2         2  ...       2        2   
4                2   68        97         1  ...       2        2   
...            ...  ...       ...       ...  ...     ...      ...   
1048570          2   40        97         2  ...       2        2   
1048571          2   51        97         2  ...       2        2   
1048572          2   55        97         2  ...       2        2   
1048573          2   28        97         2  ...       2        2   
1048574          2   52        97         2  ...       2        2   

         HIPERTENSION  OTHER_DISEASE  CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  \
0                   1              2               2        2              2   
1                   1              2               2        1              1   
2                   2              2               2        2              2   
3                   2              2               2        2              2   
4                   1              2               2        2              2   
...               ...            ...             ...      ...            ...   
1048570             2              2               2        2              2   
1048571             1              2               2        2              2   
1048572             2              2               2        2              2   
1048573             2              2               2        2              2   
1048574             2              2               2        2              2   

         TOBACCO  CLASIFFICATION_FINAL  ICU  
0              2                     3   97  
1              2                     5   97  
2              2                     3    2  
3              2                     7   97  
4              2                     3   97  
...          ...                   ...  ...  
1048570        2                     7   97  
1048571        2                     7    2  
1048572        2                     7   97  
1048573        2                     7   97  
1048574        2                     7   97  

[1048575 rows x 21 columns]

In [4]:
df.isnull().sum()

USMER                   0
MEDICAL_UNIT            0
SEX                     0
PATIENT_TYPE            0
DATE_DIED               0
INTUBED                 0
PNEUMONIA               0
AGE                     0
PREGNANT                0
DIABETES                0
COPD                    0
ASTHMA                  0
INMSUPR                 0
HIPERTENSION            0
OTHER_DISEASE           0
CARDIOVASCULAR          0
OBESITY                 0
RENAL_CHRONIC           0
TOBACCO                 0
CLASIFFICATION_FINAL    0
ICU                     0
dtype: int64

In [5]:
df=df.drop(["DATE_DIED"],axis=1)
df

USMER  MEDICAL_UNIT  SEX  PATIENT_TYPE  INTUBED  PNEUMONIA  AGE  \
0            2             1    1             1       97          1   65   
1            2             1    2             1       97          1   72   
2            2             1    2             2        1          2   55   
3            2             1    1             1       97          2   53   
4            2             1    2             1       97          2   68   
...        ...           ...  ...           ...      ...        ...  ...   
1048570      2            13    2             1       97          2   40   
1048571      1            13    2             2        2          2   51   
1048572      2            13    2             1       97          2   55   
1048573      2            13    2             1       97          2   28   
1048574      2            13    2             1       97          2   52   

         PREGNANT  DIABETES  COPD  ASTHMA  INMSUPR  HIPERTENSION  \
0               2         2     2       2        2             1   
1              97         2     2       2        2             1   
2              97         1     2       2        2             2   
3               2         2     2       2        2             2   
4              97         1     2       2        2             1   
...           ...       ...   ...     ...      ...           ...   
1048570        97         2     2       2        2             2   
1048571        97         2     2       2        2             1   
1048572        97         2     2       2        2             2   
1048573        97         2     2       2        2             2   
1048574        97         2     2       2        2             2   

         OTHER_DISEASE  CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  TOBACCO  \
0                    2               2        2              2        2   
1                    2               2        1              1        2   
2                    2               2        2              2        2   
3                    2               2        2              2        2   
4                    2               2        2              2        2   
...                ...             ...      ...            ...      ...   
1048570              2               2        2              2        2   
1048571              2               2        2              2        2   
1048572              2               2        2              2        2   
1048573              2               2        2              2        2   
1048574              2               2        2              2        2   

         CLASIFFICATION_FINAL  ICU  
0                           3   97  
1                           5   97  
2                           3    2  
3                           7   97  
4                           3   97  
...                       ...  ...  
1048570                     7   97  
1048571                     7    2  
1048572                     7   97  
1048573                     7   97  
1048574                     7   97  

[1048575 rows x 20 columns]

In [6]:
df["CLASIFFICATION_FINAL"].value_counts()

7    499250
3    381527
6    128133
5     26091
1      8601
4      3122
2      1851
Name: CLASIFFICATION_FINAL, dtype: int64

In [7]:
df.loc[(df['CLASIFFICATION_FINAL'] >= 1) & (df['CLASIFFICATION_FINAL'] < 4), 'CLASIFFICATION_FINAL'] = 1

In [8]:
df.loc[(df['CLASIFFICATION_FINAL'] >= 4) & (df['CLASIFFICATION_FINAL'] < 8), 'CLASIFFICATION_FINAL'] = 0

In [9]:
df["CLASIFFICATION_FINAL"].value_counts()

0    656596
1    391979
Name: CLASIFFICATION_FINAL, dtype: int64

In [10]:
df

USMER  MEDICAL_UNIT  SEX  PATIENT_TYPE  INTUBED  PNEUMONIA  AGE  \
0            2             1    1             1       97          1   65   
1            2             1    2             1       97          1   72   
2            2             1    2             2        1          2   55   
3            2             1    1             1       97          2   53   
4            2             1    2             1       97          2   68   
...        ...           ...  ...           ...      ...        ...  ...   
1048570      2            13    2             1       97          2   40   
1048571      1            13    2             2        2          2   51   
1048572      2            13    2             1       97          2   55   
1048573      2            13    2             1       97          2   28   
1048574      2            13    2             1       97          2   52   

         PREGNANT  DIABETES  COPD  ASTHMA  INMSUPR  HIPERTENSION  \
0               2         2     2       2        2             1   
1              97         2     2       2        2             1   
2              97         1     2       2        2             2   
3               2         2     2       2        2             2   
4              97         1     2       2        2             1   
...           ...       ...   ...     ...      ...           ...   
1048570        97         2     2       2        2             2   
1048571        97         2     2       2        2             1   
1048572        97         2     2       2        2             2   
1048573        97         2     2       2        2             2   
1048574        97         2     2       2        2             2   

         OTHER_DISEASE  CARDIOVASCULAR  OBESITY  RENAL_CHRONIC  TOBACCO  \
0                    2               2        2              2        2   
1                    2               2        1              1        2   
2                    2               2        2              2        2   
3                    2               2        2              2        2   
4                    2               2        2              2        2   
...                ...             ...      ...            ...      ...   
1048570              2               2        2              2        2   
1048571              2               2        2              2        2   
1048572              2               2        2              2        2   
1048573              2               2        2              2        2   
1048574              2               2        2              2        2   

         CLASIFFICATION_FINAL  ICU  
0                           1   97  
1                           0   97  
2                           1    2  
3                           0   97  
4                           1   97  
...                       ...  ...  
1048570                     0   97  
1048571                     0    2  
1048572                     0   97  
1048573                     0   97  
1048574                     0   97  

[1048575 rows x 20 columns]

In [20]:
df.COPD	.max()

98

In [11]:
X=df.drop(["CLASIFFICATION_FINAL"],axis=1)
y=df["CLASIFFICATION_FINAL"]
#array Conver
X=X.to_numpy()

In [12]:
#spilit data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X[:6000], y[:6000], test_size=0.10)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(5400, 19) (600, 19) (5400,) (600,)


In [13]:
import warnings
warnings.filterwarnings("ignore")
names = ["K-Nearest Neighbors", "SVM",
         "Decision Tree", "Random Forest",
         "Naive Bayes","ExtraTreesClassifier","VotingClassifier"]

from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import LinearSVC
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import ExtraTreesClassifier
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix
from sklearn.ensemble import VotingClassifier

classifiers = [
    KNeighborsClassifier(),
    LinearSVC(),
    DecisionTreeClassifier(),
    RandomForestClassifier(),
    GaussianNB(),
    ExtraTreesClassifier(),
    VotingClassifier(estimators=[('DT', DecisionTreeClassifier()), ('rf', RandomForestClassifier()), ('et', ExtraTreesClassifier())], voting='hard')]

clfF=[]
for name, clf in zip(names, classifiers):
    clf.fit(X_train, y_train)
    y_pred=clf.predict(X_test)
    print(name)
    print(confusion_matrix(y_test, y_pred))
    print(classification_report(y_test, y_pred))
    print('--------------------------------------------------------------')
    clfF.append(clf)

K-Nearest Neighbors
[[ 16  47]
 [  9 528]]
              precision    recall  f1-score   support

           0       0.64      0.25      0.36        63
           1       0.92      0.98      0.95       537

    accuracy                           0.91       600
   macro avg       0.78      0.62      0.66       600
weighted avg       0.89      0.91      0.89       600

--------------------------------------------------------------
SVM
[[ 18  45]
 [  4 533]]
              precision    recall  f1-score   support

           0       0.82      0.29      0.42        63
           1       0.92      0.99      0.96       537

    accuracy                           0.92       600
   macro avg       0.87      0.64      0.69       600
weighted avg       0.91      0.92      0.90       600

--------------------------------------------------------------
Decision Tree
[[ 30  33]
 [ 34 503]]
              precision    recall  f1-score   support

           0       0.47      0.48      0.47        63
    

In [14]:
clfF[1].predict([X[1]])

array([0], dtype=int64)

In [16]:
import pickle
pickle.dump(clfF, open("model.pkl", 'wb'))     